name: Release and Deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create GitHub Release and upload HTML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create GitHub Release and upload asset
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            timetable_viewer.html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy_pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare publish directory
        run: |
          mkdir -p public
          cp timetable_viewer.html public/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
